version: '3.3'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - "./scripts/schema_and_users.sql:/docker-entrypoint-initdb.d/1.sql"
